### PR TITLE
Update tmLanguage grammar

### PR DESCRIPTION
**Pull request by Laegluin**
This updates the tmLanguage grammar for gluon and also adds some new rules:

- remove `and`, add `rec` keyword
- move `type`, `let` and `in` to normal keyword
- rule for `True` and `False` as `constant.language.boolean`
- add `|` and `?` as operator
- rules for macros and attributes
- rule for function definitions with let/lambdas
- special handling of `?` when used for implicits
- rule for types in type annotations (after `:`) and type definitions

This is quite hacky, but at least when looking at the standard library, things seem to work. These are obviously a quite lot of changes, and the difference in highlighting is pretty extreme (there's a lot more color now).

On a side note, is there any specific reason the file is in XML? Working with JSON/YAML would probably be a bit nicer.

### CODE REVIEW

**Comment by Marwes** [comment]
Seems fine I think, forgotten to keep this updated since I usually use vim now (used to use VSCode with this).

The only reason it is in XML is that I wasn't aware other formats were supported, I found an OCaml or F# definition which I based this on (and that happened to be in XML). Probably tedious to change it now but if you want I'd be happy to have JSON or YAML file instead!

**Comment by Laegluin** [comment]
I think there are converters for this, I'll try some and see what happens.

Am 11.12.2018 23:11 schrieb Markus Westerlind <notifications@github.com>:

Seems fine I think, forgotten to keep this updated since I usually use vim now (used to use VSCode with this).

The only reason it is in XML is that I wasn't aware other formats were supported, I found an OCaml or F# definition which I based this on (and that happened to be in XML). Probably tedious to change it now but if you want I'd be happy to have JSON or YAML file instead!

**Comment by Laegluin** [comment]
Was easy enough, the grammar is now in JSON :)

**Comment by Marwes** [comment]
That is much easier to read!

Looks good, thanks! Was a while since I updated the VSCode addon (and not just the Rust part on crates.io). Will try and do it fairly soon in conjunction with publishing a first version of extensible effects.

**Comment by Laegluin** [comment]
The VSCode plugin works pretty well actually!

Sometimes it crashes on some index out of bounds error, but it's not often enough that I have actually bothered to track it down, and that's the only problem I've had.

**Comment by Marwes** [comment]
If you can get a stacktrace out of it I'd be happy with just an issue!

**Comment by Laegluin** [comment]
> If you can get a stacktrace out of it I'd be happy with just an issue!

Will do if it happens again, may take while though, like I said it wasn't exactly common :)

**Pull request merged**
