### PR TITLE
[WIP] fix: lsp deadlock bug

### PR DESCRIPTION
**Pull request by Shuenhoy**
There is some deadlock bug in the LSP server, which makes the VSCode extension almost unusable. 
In general, the bug happens because a mutex is locked when it is already locked in the same thread like this:

```
mutex.lock() //A
|a()
|  -> b()
|       -> ...
|            -> mutex.lock()
mutex.unlock() 
```
In fact, there is no need to hold the mutex lock for such a long time for A. And that is how the bug is fixed.

- - -
There seems to still be some problems, I would re-test it.

### CODE REVIEW

**Comment by Shuenhoy** [comment]
https://github.com/rust-lang/rust/issues/75313 causes the CI build failure.

**Comment by Shuenhoy** [comment]
It seems there are still some times deadlock would happen after the current fix, but I cannot easily reproduce.

**Comment by Shuenhoy** [comment]
There are still some situations, the LSP server would get stuck. However, I can hardly reproduce this. Doing some random typing for a long time sometimes causes this. I am not sure it is the same deadlock issue. Anywhere, after this fix, the LSP server would not be stuck in most situations.

**Comment by Marwes** [comment]
Thanks for the PR! I believe I made the same fixes in https://github.com/gluon-lang/gluon_language-server/pull/36 which should have been released (or at least have sat in the PR queue if I hadn't forgotten :( ). I don't remember seeing any lock ups after that, but I haven't had a chance to use that change for to long.

> rust-lang/rust#75313 causes the CI build failure.

Nice to see that fixed, I have noticed that issue but after searching through the issue tracker I actually didn't submit a new issue since I saw what I figured were identical reports already.

**Comment by Shuenhoy** [comment]
> Thanks for the PR! I believe I made the same fixes in #36 which should have been released (or at least have sat in the PR queue if I hadn't forgotten :( ). I don't remember seeing any lock ups after that, but I haven't had a chance to use that change for to long.
> 
> > [rust-lang/rust#75313](https://github.com/rust-lang/rust/issues/75313) causes the CI build failure.
> 
> Nice to see that fixed, I have noticed that issue but after searching through the issue tracker I actually didn't submit a new issue since I saw what I figured were identical reports already.

I didn't succeed in finding all the issues, so it's good news that you have fixed it completely, which means there will be a usable LSP. Closing the PR.

**Pull request closed without merging**
